package com.woodev.teamcloud.prompt.gpt.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;
import lombok.experimental.SuperBuilder;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.UUID;

@Getter
@Setter
@SuperBuilder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "prompt")
public class GPTAPIKey {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "entityNameIdIndex")
    private UUID id;

    @DynamoDBAttribute
    @Builder.Default
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "entityNameIdIndex")
    private String entityName = "GPT_API_KEY";

    @DynamoDBAttribute
    private String key;
}
