package com.woodev.teamcloud.prompt.gpt.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;
import lombok.experimental.SuperBuilder;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.UUID;

@Getter
@Setter
@SuperBuilder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "prompt")
public class VersioningPrompt {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "entityNameIdIndex")
    private UUID id;

    @DynamoDBAttribute
    @Builder.Default
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "entityNameIdIndex")
    private String entityName = "PROMPT";

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "promptNamePromptVersionIndex")
    private String promptName;

    @DynamoDBAttribute
    @Builder.Default
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "promptNamePromptVersionIndex")
    private String promptVersion = newPromptVersion();

    @DynamoDBAttribute
    private String aiModel;

    @DynamoDBAttribute
    private String aiModelVersion;

    @DynamoDBAttribute
    private String description;

    @DynamoDBAttribute
    private GPTAPIOptions params;

    @DynamoDBAttribute
    private List<GPTMessage> messages;

    private static String newPromptVersion() {
        // 현재 시간을 기반으로 버전을 생성
        // "yyyy-mm-dd-hh-mm-ss"
        return LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd-HH:mm:ss"));
    }
}
