package com.woodev.teamcloud.team.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

import java.util.UUID;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "team")
public class Team {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "entityNameIdIndex")
    private UUID id;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    @Builder.Default
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "entityNameIdIndex")
    private String entityName = "TEAM";
}
